  } catch(test1::fehler())		// function type promoted to pointer
  void func(int a) {
int main() {
